name: spectrum_kids
description: E-learning gaming application for kids

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: ^0.4.5+11
  cached_network_image: ^2.3.2+1
  dio: ^3.0.9
  fluentui_system_icons: ^1.1.85
  flutter_custom_clippers: ^1.1.1
  flutter_downloader: ^1.5.0
  flutter_masked_text: ^0.8.0
  flutter_native_splash: ^0.1.9
  flutter_svg: ^0.19.0
  freezed_annotation: ^0.12.0
  fresh_dio: ^0.2.0
  google_fonts: ^1.1.0
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  http: ^0.12.0+1
  image_gallery_saver: ^1.6.1
  imei_plugin: ^1.1.6
  intl: ^0.16.1
  json_annotation: ^3.0.1
  loading_hud: ^0.2.0
  material_design_icons_flutter: ^4.0.5855
  moor: ^3.4.0
  moor_flutter: ^3.1.0
  page_view_indicator: ^2.0.4
  path: ^1.7.0
  path_provider: ^1.6.10
  percent_indicator: ^2.1.1
  permission_handler: ^5.0.1+1
  provider: ^4.1.3
  salomon_bottom_bar: ^2.0.0
  shared_preferences: ^0.5.12+4
  webview_flutter_plus: ^0.1.1+9
  flutter_sound: ^4.0.0
  audioplayers: ^0.14.0
  flutter_colorpicker: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.5
  freezed: ^0.12.2
  hive_generator: ^0.8.2
  json_serializable: ^3.4.1
  moor_generator: ^3.4.0


# dependency_overrides:
#   meta: 1.2.0
flutter_native_splash:
  image: assets/images/splash_screen_two.png
  color: "ffffff"
  # fill: false
  # android

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/spectrum-logo.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/fruits/
    - assets/
    - assets/audio/
    - assets/data/
    - assets/music/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
